package net.sjhub.upgradednetheritereforged.config;

public class UpgradedNetheriteConfig {
   public static boolean DisableTooltips;
   public static boolean AltTextures;
   public static boolean OldTextures;
   public static int UpgradedPlayerGoldArmorRequireSet = 4;
   public static int UpgradedPlayerFireArmorRequireSet = 4;
   public static int UpgradedPlayerEnderArmorRequireSet = 4;
   public static int UpgradedPlayerWaterArmorRequireSet = 4;
   public static int UpgradedPlayerWitherArmorRequireSet = 4;
   public static int UpgradedPlayerPoisonArmorRequireSet = 4;
   public static int UpgradedPlayerPhantomArmorRequireSet = 4;
   public static int UpgradedPlayerFeatherArmorRequireSet = 4;
   public static int UpgradedPlayerEchoArmorRequireSet = 4;
   public static boolean EnablePiglinNeutral;
   public static boolean EnableLuckBonus;
   public static int LuckBonus = 2;
   public static boolean EnableDamageBonusGoldWeapon;
   public static int DamageBonusGoldWeapon = 10;
   public static boolean EnableLootingBonus;
   public static int LootingBonus = 1;
   public static int LootingEnchantBonus = 1;
   public static boolean EnableFortuneBonus;
   public static int FortuneBonus = 1;
   public static int FortuneEnchantBonus = 1;
   public static boolean EnableFireImmune;
   public static boolean EnableLavaSpeed;
   public static boolean EnableDamageDurabilityFireArmor;
   public static int DelayDamageDurabilityFireArmor = 20;
   public static int DamageDurabilityFireArmor = 1;
   public static boolean EnableAutoSmelt;
   public static boolean EnableAutoSmeltFortune;
   public static boolean EnableDamageBonusFireWeapon;
   public static int DamageBonusFireWeapon = 4;
   public static int DamageBonusFireEnchantWeapon = 3;
   public static boolean EnableVoidSave;
   public static boolean EnablePreventAnger;
   public static boolean EnableBreakEnderArmor;
   public static boolean EnableDamageBonusEnderWeapon;
   public static int DamageBonusEnderWeapon = 4;
   public static boolean EnablePreventTeleport;
   public static boolean EnableDoubleLootingBonusEnderWeapon;
   public static boolean EnableTeleportChest;
   public static boolean EnableWaterBreath;
   public static boolean EnableWaterSpeed;
   public static boolean EnableDamageDurabilityWaterArmor;
   public static int DelayDamageDurabilityWaterArmor = 20;
   public static int DamageDurabilityWaterArmor = 1;
   public static boolean EnableDamageBonusWaterWeapon;
   public static int DamageBonusWaterWeapon = 10;
   public static boolean EnableDamageBonusWaterEndermanWeapon;
   public static int DamageBonusWaterEndermanWeapon = 10;
   public static boolean EnableMiningSpeedUnderwater;
   public static boolean EnableElderGuardianDebuffImmune;
   public static boolean EnableWitherImmune;
   public static boolean EnableDamageDurabilityWitherArmor;
   public static int DelayDamageDurabilityWitherArmor = 20;
   public static int DamageDurabilityWitherArmor = 5;
   public static boolean EnableDamageBonusWitherWeapon;
   public static int DamageBonusWitherWeapon = 4;
   public static boolean EnableWitherEffect;
   public static boolean EnablePoisonImmune;
   public static boolean EnableClimbWall;
   public static boolean EnableDamageDurabilityPoisonArmor;
   public static int DelayDamageDurabilityPoisonArmor = 20;
   public static int DamageDurabilityPoisonArmor = 5;
   public static boolean EnableDamageBonusPoisonWeapon;
   public static int DamageBonusPoisonWeapon = 4;
   public static boolean EnablePoisonEffect;
   public static boolean EnableFallImmune;
   public static boolean EnableStepHeight;
   public static boolean EnableDamageDurabilityPhantomArmor;
   public static int MultiplierDamageDurabilityPhantomArmor = 1;
   public static boolean EnableDamageBonusPhantomWeapon;
   public static int DamageBonusPhantomWeapon = 10;
   public static boolean EnableGlowingEffect;
   public static boolean EnableReachEffect;
   public static int BonusReachTool = 2;
   public static boolean EnableWaterLavaWalking;
   public static boolean EnableMultiJump;
   public static int MultiJump;
   public static boolean EnableReduceFallDamage;
   public static boolean EnableWaterDamageDurabilityFeatherArmor;
   public static boolean EnableLavaDamageDurabilityFeatherArmor;
   public static boolean EnableFallDamageDurabilityFeatherArmor;
   public static int DelayDamageDurabilityFeatherArmor = 20;
   public static int DamageDurabilityFeatherArmor = 1;
   public static boolean EnableAttractItem;
   public static boolean EnableLevitationImmune;
   public static boolean EnableHealthMalus;
   public static int HealthMalus = 10;
   public static boolean EnableDamageBonusCorruptWeapon;
   public static int DamageBonusCorruptWeapon = 7;
   public static boolean EnableLootingBonusCorruptWeapon;
   public static int LootingBonusCorruptWeapon = 2;
   public static boolean EnableFortuneBonusCorruptTool;
   public static int FortuneBonusCorruptTool = 2;
   public static boolean EnableSoulbound;
   public static boolean EnableKeepItemsChance;
   public static int KeepItemsChance = 50;
   public static boolean EnableReduceDamageEchoArmor;
   public static int ReduceDamageEchoArmor = 50;
   public static boolean EnableHealEchoArmor;
   public static int HealEchoArmorDelay = 20;
   public static boolean EnableDamageBonusEchoWeapon;
   public static int DamageBonusEchoWeapon = 10;
   public static boolean EnableBonusExpEcho;
   public static int MinExpEcho = 2;
   public static int MaxExpEcho = 5;
}
